apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-influx-disk
  namespace: jmeter-reporting
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-grafana-disk
  namespace: jmeter-reporting
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi