apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  labels:
    app: main-config
data:
  load_test: |
    #!/bin/bash
    : '
      ===============================================================================================
      ||            Script invokes jmeter test script with the workers POD IP addresses            ||
      ||       Script should be run like: ./load_test "path to the test script in jmx format"      ||
      ||   HTML dashbord is created at the end of the run and can be seen in azure build pipeline  ||
      ===============================================================================================
    '

    : '
      ==========================================
      ||          $1 - JMX file name          ||
      ||    $2 - Blob storage account name    ||
      ||    $3 - Blob storage account key     ||
      ||   $4 - Blob storage container name   ||
      ==========================================
    '

    testStartTime=$(date +"%T")

    /opt/apache-jmeter-5.5/bin/jmeter.sh -n -t $1 -l results.csv -e -o /results/ \
      -GcustomConfig.properties -Dserver.rmi.ssl.disable=true -X \
      -R `getent ahostsv4 jmeter-workers-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`

    if [ ! -z "$2" ] && [ ! -z "$3"] && [ ! -z "$4"]; then
      echo "${BLOB_ACCOUNT_NAME}"
      echo "${BLOB_KEY}"
      echo "${BLOB_CONTAINER_NAME}"
      az storage blob upload \
        --account-name "$2" \
        --account-key "$3" \
        --container-name "$4" \
        --overwrite true \
        --file results.csv \
        --name $1-$testStartTime.csv

      echo "Results have been pushed to: https://$2.blob.core.windows.net/$4/$1.csv"
    fi

    mv /opt/apache-jmeter-5.5/bin/jmeter.log /results/jmeter.log
    mv customConfig.properties /results/customConfig.properties
    mv results.csv /results/results.csv